apiVersion: apps/v1
kind: Deployment
metadata:
  name: outgoerbackendcoresandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outgoerbackendcoresandbox
  template:
    metadata:
      labels:
        app: outgoerbackendcoresandbox
    spec:
      containers:
        - name: outgoerbackendcoresandbox
          env:
            - name: APP_KEY
              value: base64:Jd9Tkt7uuZDy/JOcOl7QUiPTNuF7Jbu59vRyIALMgbM=
            - name: APACHE_SERVER_NAME
              value: "localhost"
          image: backendcoresandboxacr.azurecr.io/outgoerbackendcoresandbox                
          ports:
            - containerPort: 80
