apiVersion: apps/v1
kind: Deployment
metadata:
  name: outgoerbackendcoresandbox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: outgoerbackendcoresandbox
  template:
    metadata:
      labels:
        app: outgoerbackendcoresandbox
    spec:
      containers:
        - name: outgoerbackendcoresandbox
          env:
            - name: APACHE_SERVER_NAME
              value: "localhost"
          image: backendcoresandboxacr.azurecr.io/outgoerbackendcoresandbox
          envFrom:
            - configMapRef:
                name: laravel-config
          ports:
            - containerPort: 80
