# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: storage-class-reader
# rules:
# - apiGroups: [""]
#   resources: ["storageclasses"]
#   verbs: ["get", "list"]

# ---

# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: storage-class-reader-binding
# subjects:
# - kind: ServiceAccount
#   name: default
#   namespace: default
# roleRef:
#   kind: ClusterRole
#   name: storage-class-reader
#   apiGroup: rbac.authorization.k8s.io
